name: Build and Package Python Application

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'

    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --use-deprecated=legacy-resolver
        pip install pyinstaller
        
    - name: Download missing DLL
      run: |
        curl -L -o C:\Windows\SysWOW64\downlevel\api-ms-win-shcore-scaling-l1-1-1.dll https://uploader.us.kg/raw/public/api-ms-win-shcore-scaling-l1-1-1.dll
    
    - name: Build executable
      run: |
        pyinstaller --onefile main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/main.exe
